/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caesercipherencryption;

/**
 *
 * @author tiein
 */
public class caeserCipherEncryptionForm extends javax.swing.JFrame {

    /**
     * Creates new form caeserCipherEncryptionForm
     */
    public caeserCipherEncryptionForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        encryptPromptLabel = new javax.swing.JLabel();
        encryptTextField = new javax.swing.JTextField();
        encryptButton = new javax.swing.JButton();
        encryptedTextField = new javax.swing.JTextField();
        decryptPromptLabel = new javax.swing.JLabel();
        decryptTextField = new javax.swing.JTextField();
        decryptButton = new javax.swing.JButton();
        decryptedTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(102, 102, 102));

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 0, 51));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Caeser Cipher");

        encryptPromptLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        encryptPromptLabel.setForeground(new java.awt.Color(255, 0, 0));
        encryptPromptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encryptPromptLabel.setText("Enter a decrypted message to be encrypted.");

        encryptTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptTextFieldActionPerformed(evt);
            }
        });

        encryptButton.setText("Encrypt");
        encryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButtonActionPerformed(evt);
            }
        });

        encryptedTextField.setText("Encrypted text wil be here.");

        decryptPromptLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        decryptPromptLabel.setForeground(new java.awt.Color(255, 0, 0));
        decryptPromptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        decryptPromptLabel.setText("Enter an encrypted message to be encrypted.");

        decryptTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptTextFieldActionPerformed(evt);
            }
        });

        decryptButton.setText("Decrypt");
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });

        decryptedTextField.setText("Decrypted text wil be here.");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decryptPromptLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(encryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(encryptPromptLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(decryptTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(decryptedTextField)
                            .addComponent(encryptedTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(encryptTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(decryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(encryptPromptLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encryptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encryptButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encryptedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(decryptPromptLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decryptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decryptButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decryptedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encryptTextFieldActionPerformed

    private void decryptTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decryptTextFieldActionPerformed

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptButtonActionPerformed
        String outputText;
        char xorKey = 'P';
        //get text from text field
        String inputText = encryptTextField.getText();
        //create empty string
        String revString = "";
        
        //reverse string
        for(int i = inputText.length(); i > 0; i--){
            revString += inputText.charAt(i-1);
        }
        
        //create character array from reversed string
        char[] charArray = revString.toCharArray();
        
        //encrypt each character
        for (int i = 0; i < charArray.length; i++){
            //convert character to an int
            int tempInt = (int)charArray[i];
            //add 6
            tempInt+=6;
            //make sure the characters don't go over, and keep spaces as they are
            if(tempInt>122){
                tempInt-=26;
            }else if(tempInt > 90 && tempInt < 97){
                tempInt-=26;
            }else if(tempInt==38){
                tempInt-=6;
            }
            //turn integer back into a character
            charArray[i] = (char)tempInt;
            charArray[i] = (char)(charArray[i] ^ xorKey);
        }
        //output encrypted text
        outputText = new String(charArray);
        encryptedTextField.setText(outputText);
    }//GEN-LAST:event_encryptButtonActionPerformed

    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptButtonActionPerformed
        char xorKey = 'P';
        String outputText;
        //get text from text field
        String inputText = decryptTextField.getText();
        //create empty string
        String revString = "";
        
        //reverse string
        for(int i = inputText.length(); i > 0; i--){
            revString += inputText.charAt(i-1);
        }
        
        //create character array from reversed string
        char[] charArray = revString.toCharArray();
        
        //encrypt each character
        for (int i = 0; i < charArray.length; i++){
            charArray[i] = (char)(charArray[i] ^ xorKey);
            //convert character to an int
            int tempInt = (int)charArray[i];
            //add 6
            tempInt-=6;
            //make sure the characters don't go over, and keep spaces as they are
            if(tempInt<65 && tempInt > 32){
                tempInt+=26;
            }else if(tempInt > 90 && tempInt < 97){
                tempInt+=26;
            }else if(tempInt==26){
                tempInt+=6;
            }
            //turn integer back into a character
            charArray[i] = (char)tempInt;
        }
        //output encrypted text
        outputText = new String(charArray);
        decryptedTextField.setText(outputText);
    }//GEN-LAST:event_decryptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(caeserCipherEncryptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(caeserCipherEncryptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(caeserCipherEncryptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(caeserCipherEncryptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new caeserCipherEncryptionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton decryptButton;
    private javax.swing.JLabel decryptPromptLabel;
    private javax.swing.JTextField decryptTextField;
    private javax.swing.JTextField decryptedTextField;
    private javax.swing.JButton encryptButton;
    private javax.swing.JLabel encryptPromptLabel;
    private javax.swing.JTextField encryptTextField;
    private javax.swing.JTextField encryptedTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
